var alphabet = [
    {char:"A",name:"aleph",pic:"G1"},
    {char:"i",name:"yod",pic:"M17"},
    {char:"y",name:"y",pic:"M17 M17"},
    {char:"a",name:"ayin",pic:"D36"},
    {char:"w",name:"w",pic:"G43"},
    {char:"b",name:"b",pic:"D58"},
    {char:"p",name:"p",pic:"Q3"},
    {char:"f",name:"f",pic:"I9"},
    {char:"m",name:"m",pic:"G17"},
    {char:"n",name:"n",pic:"N35"},
    {char:"r",name:"r",pic:"D21"},
    {char:"h",name:"h",pic:"O4"},
    {char:"H",name:"dotted h",pic:"V28"},
    {char:"x",name:"third h",pic:"Aa1"},
    {char:"X",name:"fourth h",pic:"F32"},
    {char:"z",name:"z or first s",pic:"O34"},
    {char:"s",name:"s or second s",pic:"S29"},
    {char:"S",name:"shin",pic:"N37"},
    {char:"q",name:"q",pic:"N29"},
    {char:"k",name:"k",pic:"V31"},
    {char:"g",name:"g",pic:"W12"},
    {char:"t",name:"t",pic:"X1"},
    {char:"T",name:"second t",pic:"V13"},
    {char:"d",name:"d",pic:"D46"},
    {char:"D",name:"second d",pic:"I10"}
];

var multiliteralSigns = [
    {chars:"Aw",pic:"F40",desc:"spine and spinal cord"},
    {chars:"Ab",pic:"U23",desc:"chisel"},
    {chars:"mr",pic:"U23",desc:"chisel"},
    {chars:"Ax",pic:"G25",desc:"crested ibis"},
    {chars:"Ax",pic:"M15",desc:"clump of papyrus with buds"},
    {chars:"iw",pic:"D54",desc:"walking legs"},
    {chars:"iw",pic:"E9",desc:"newborn bubalis"},
    {chars:"ib",pic:"F34",desc:"heart"},
    {chars:"ib",pic:"E8",desc:"kid"},
    {chars:"im",pic:"Z11",desc:"crossed planks"},
    {chars:"im",pic:"Aa13",desc:"unknown"},
    {chars:"in",pic:"W25",desc:"pot with legs"},
    {chars:"in",pic:"K1",desc:"bulti"},
    {chars:"in",pic:"W24",desc:"pot"},
    {chars:"in",pic:"A27",desc:"man running"},
    {chars:"ir",pic:"D4",desc:"eye"},
    {chars:"ir",pic:"A48",desc:"seated man with knife"},
    {chars:"iz",pic:"M40",desc:"tied bundle of reeds"},
    {chars:"is",pic:"Q1",desc:"seat"},
    {chars:"st",pic:"Q1",desc:"seat"},
    {chars:"is",pic:"F51",desc:"piece of meat"},
    {chars:"ik",pic:"A19",desc:"old, distinguished"},
    {chars:"it",pic:"V15",desc:"hobble with legs"},
    {chars:"iT",pic:"V15",desc:"hobble with legs"},
    {chars:"aA",pic:"O29",desc:"wood column"},
    {chars:"ab",pic:"F16",desc:"horn"},
    {chars:"aH",pic:"T24",desc:"fishing net"},
    {chars:"aq",pic:"G35",desc:"cormorant"},
    {chars:"ad",pic:"V26",desc:"spool with thread"},
    {chars:"aD",pic:"V26",desc:"spool with thread"},
    {chars:"aD",pic:"K3",desc:"mullet"},
    {chars:"wA",pic:"V4",desc:"lasso"},
    {chars:"wa",pic:"T21",desc:"harpoon"},
    {chars:"wp",pic:"F13",desc:"horns"},
    {chars:"wn",pic:"E34",desc:"hare"},
    {chars:"wn",pic:"M42",desc:"rosette"},
    {chars:"wr",pic:"G37",desc:"forktailed swallow"},
    {chars:"wd",pic:"V24",desc:"cord wound on stick"},
    {chars:"wD",pic:"V24",desc:"cord wound on stick"},
    {chars:"bA",pic:"G29",desc:"saddle-billed stork"},
    {chars:"bA",pic:"W10A",desc:"pot"},
    {chars:"bH",pic:"F18",desc:"tusk"},
    {chars:"Hw",pic:"F18",desc:"tusk"},
    {chars:"pA",pic:"G40",desc:"pintail duck flying"},
    {chars:"pA",pic:"G41",desc:"pintail duck landing"},
    {chars:"pH",pic:"F22",desc:"hindquarters of feline"},
    {chars:"pd",pic:"D56",desc:"leg"},
    {chars:"pd",pic:"T9",desc:"bow"},
    {chars:"pD",pic:"T9",desc:"bow"},
    {chars:"mA",pic:"U1",desc:"sickle"},
    {chars:"mi",pic:"W19",desc:"milk jug with handle"},
    {chars:"mi",pic:"D38",desc:"forearm with bread"},
    {chars:"mw",pic:"N35A",desc:"three ripples of water"},
    {chars:"mn",pic:"Y5",desc:"game board and pieces"},
    {chars:"mn",pic:"T1",desc:"macewith flat head"},
    {chars:"mr",pic:"U7",desc:"hoe"},
    {chars:"mr",pic:"N36",desc:"canal"},
    {chars:"mr",pic:"O5",desc:"winding wall"},
    {chars:"nm",pic:"O5",desc:"winding wall"},
    {chars:"mH",pic:"V22",desc:"whip"},
    {chars:"ms",pic:"F31",desc:"three fox skins"},
    {chars:"mt",pic:"D52",desc:"penis"},
    {chars:"mt",pic:"G14",desc:"vulture"},
    {chars:"md",pic:"S43",desc:"staff"},
    {chars:"ni",pic:"D35",desc:"gesture of negation"},
    {chars:"ni",pic:"D41",desc:"forearm with palm down"},
    {chars:"nw",pic:"W24",desc:"pot"},
    {chars:"nw",pic:"U19",desc:"adze"},
    {chars:"nb",pic:"V30",desc:"basket"},
    {chars:"nm",pic:"T34",desc:"butcher knife"},
    {chars:"nn",pic:"M22 M22",desc:"rush"},
    {chars:"nH",pic:"G21",desc:"guinea-fowl"},
    {chars:"ns",pic:"F20",desc:"tongue"},
    {chars:"nD",pic:"Aa27",desc:"spindle"},
    {chars:"rw",pic:"E23",desc:"lion recumbent"},
    {chars:"rs",pic:"T13",desc:"pieces of wood tied"},
    {chars:"hb",pic:"U13",desc:"plow"},
    {chars:"HA",pic:"M16",desc:"clump of papyrus"},
    {chars:"Hp",pic:"Aa5",desc:"part of a ship"},
    {chars:"Hm",pic:"D280A",desc:"pelvis and vulva"},
    {chars:"Hm",pic:"U36",desc:"launderer's club"},
    {chars:"Hn",pic:"M2",desc:"plant"},
    {chars:"Hn",pic:"V36",desc:"receptacle of cloth"},
    {chars:"Hn",pic:"U8",desc:"hoe"},
    {chars:"Hr",pic:"D2",desc:"face"},
    {chars:"Hr",pic:"N31",desc:"path with shrubs"},
    {chars:"Hz",pic:"W14",desc:"water jar"},
    {chars:"Hs",pic:"W14",desc:"water jar"},
    {chars:"HD",pic:"T3",desc:"mace with round head"},
    {chars:"xA",pic:"M12",desc:"lotus (water lily) plant"},
    //{chars:"xA",pic:"L6",desc:"shell"},
    {chars:"xa",pic:"N28",desc:"sun's ray above hill"},
    {chars:"xw",pic:"D43",desc:"forearm with flail"},
    {chars:"xm",pic:"R22",desc:"min emblem"},
    {chars:"xt",pic:"M3",desc:"stick"},
    {chars:"XA",pic:"K4",desc:"oxyrhynchus"},
    {chars:"Xn",pic:"F26",desc:"goatskin"},
    {chars:"Xn",pic:"D33",desc:"arms and oar"},
    {chars:"zA",pic:"G39",desc:"pintail duck"},
    {chars:"gb",pic:"G38",desc:"goose"},
    {chars:"zA",pic:"V16",desc:"hobble for cattle"},
    {chars:"zA",pic:"V17",desc:"rolled up tent"},
    {chars:"zp",pic:"O50",desc:"threshing floor with grain"},
    {chars:"sA",pic:"Aa17",desc:"lid of a chest"},
    {chars:"sw",pic:"M23",desc:"sedge"},
    {chars:"sn",pic:"T22",desc:"arrowhead and spear"},
    {chars:"sk",pic:"V29",desc:"swab"},
    {chars:"st",pic:"F29",desc:"cowskin with arrow"},
    {chars:"sT",pic:"S22",desc:"shoulder knot"},
    {chars:"sD",pic:"Z9",desc:"crossed sticks"},
    {chars:"SA",pic:"M8",desc:"pool with lotuses"},
    {chars:"Sw",pic:"H6",desc:"feather"},
    {chars:"Sm",pic:"N40",desc:"depression with legs"},
    {chars:"Sn",pic:"V7",desc:"cord with ends down"},
    {chars:"Sn",pic:"V1",desc:"coil of rope"},
    {chars:"Ss",pic:"V6",desc:"cord with ends up"},
    {chars:"Sd",pic:"F30",desc:"water-skin"},
    {chars:"qn",pic:"Aa8",desc:"irrigation channel"},
    {chars:"qs",pic:"T19",desc:"bone harpoon head"},
    {chars:"qd",pic:"Aa28",desc:"builder's level"},
    {chars:"kA",pic:"D28",desc:"two arms"},
    {chars:"kp",pic:"R5",desc:"censer"},
    {chars:"km",pic:"I6",desc:"crocodile scales"},
    {chars:"gm",pic:"G28",desc:"black ibis"},
    {chars:"gs",pic:"Aa16",desc:"unknown"},
    {chars:"tA",pic:"U30",desc:"kiln"},
    {chars:"tA",pic:"N16",desc:"strip of land with sand"},
    {chars:"ti",pic:"U33",desc:"pestle"},
    {chars:"tm",pic:"U15",desc:"sled"},
    {chars:"TA",pic:"G47",desc:"duckling"},
    {chars:"di",pic:"D37",desc:"forearm with bread mold"},
    {chars:"di",pic:"X8",desc:"bread mold"},
    {chars:"db",pic:"G22",desc:"hoopoe"},
    {chars:"dp",pic:"D1",desc:"head"},
    {chars:"dp",pic:"T8",desc:"dagger"},
    {chars:"DA",pic:"U28",desc:"fire drill"},
    {chars:"Dw",pic:"N26",desc:"mountain"},
    {chars:"Dr",pic:"M36",desc:"bundle of flax"},
    {chars:"Dd",pic:"R11",desc:"reed column"},
    {chars:"nni",pic:"A17",desc:"child"},
    {chars:"xnt",pic:"D19",desc:"face in profile/nose/face"},
    {chars:"iwt",pic:"D35",desc:"negation (that not)"},
    {chars:"iwti",pic:"D35",desc:"negation (which not)"},
    {chars:"wsr",pic:"F12",desc:"head and neck of jackal"},
    {chars:"sDm",pic:"F21",desc:"ear of bovine"},
    {chars:"idn",pic:"F21",desc:"ear of bovine"},
    {chars:"wHm",pic:"F25",desc:"leg and hoof of ox"},
    {chars:"sAb",pic:"F28",desc:"cowskin/dappled"},
    {chars:"nfr",pic:"F35",desc:"heart and windpipe"},
    {chars:"zmA",pic:"F36",desc:"lung and windpipe"},
    {chars:"isw",pic:"F44",desc:"joint of meat"},
    {chars:"spHr",pic:"F50",desc:"folded cloth and intestine"},
    {chars:"tiw",pic:"G4",desc:"buzzard"},
    {chars:"miwt",pic:"G14",desc:"vulture"},
    {chars:"mit",pic:"G14",desc:"vulture"},
    {chars:"mwt",pic:"G14",desc:"vulture"},
    {chars:"dSr",pic:"G27",desc:"flamingo/red"},
    {chars:"mAw",pic:"G46",desc:"quail chick and sickle"},
    {chars:"snd",pic:"G54",desc:"plucked bird"},
    {chars:"snD",pic:"G54",desc:"plucked bird"},
    {chars:"pAq",pic:"H2",desc:"head of a crested bird"},
    {chars:"wSm",pic:"H2",desc:"head of a crested bird"},
    {chars:"pAq",pic:"H3",desc:"head of a spoonbill"},
    {chars:"xpr",pic:"L1",desc:"scarab beetle"},
    {chars:"imA",pic:"G17",desc:"tree"},
    {chars:"wAd",pic:"M13",desc:"papyrus"},
    {chars:"wAD",pic:"M13",desc:"papyrus"},
    {chars:"nxb",pic:"M22",desc:"rush"},
    {chars:"Sma",pic:"M26",desc:"flowering sedge"},
    {chars:"nDm",pic:"M29",desc:"carob pod"},
    {chars:"wbn",pic:"N8",desc:"sun with rays"},
    {chars:"psD",pic:"N9",desc:"moon"},
    {chars:"sbA",pic:"N14",desc:"star"},
    {chars:"dwA",pic:"N14",desc:"star"},
    // {chars:"wdb",pic:"N20",desc:"tongue of land"},
    // {chars:"wDb",pic:"N20",desc:"tongue of land"},
    {chars:"iwn",pic:"O28",desc:"column with tenon"},
    {chars:"Szp",pic:"O43",desc:"fence"},
    {chars:"sSp",pic:"O43",desc:"fence"},
    {chars:"zpi",pic:"O50",desc:"threshing floor with grain"},
    {chars:"wHa",pic:"P4",desc:"boat with net"},
    {chars:"aHa",pic:"P6",desc:"mast"},
    {chars:"xrw",pic:"P8",desc:"oar"},
    {chars:"xtm",pic:"Q1",desc:"seat"},
    {chars:"Htp",pic:"R4",desc:"bread loaf on mat"},
    {chars:"kAp",pic:"R5",desc:"censer"},
    {chars:"mDH",pic:"S10",desc:"headband"},
    // {chars:"wsx",pic:"S11",desc:"broad collar"},
    {chars:"dmd",pic:"S23",desc:"knotted cloth"},
    {chars:"dmD",pic:"S23",desc:"knotted cloth"},
    {chars:"TAz",pic:"S24",desc:"knotted belt"},
    // {chars:"smA",pic:"S31",desc:"folded cloth and horned viper"},
    {chars:"siA",pic:"S32",desc:"cloth with fringe"},
    {chars:"abx",pic:"S34",desc:"sandal strap"},
    {chars:"HqA",pic:"S38",desc:"crook"},
    {chars:"awt",pic:"S39",desc:"shepherd's crook"},
    {chars:"wAs",pic:"S40",desc:"animal-headed staff"},
    {chars:"Dam",pic:"S40",desc:"animal-headed staff"},
    {chars:"sxm",pic:"S42",desc:"sceptre"},
    {chars:"xDD",pic:"T6",desc:"mace with vipers"},
    {chars:"zwn",pic:"T11",desc:"arrow"},
    {chars:"rwd",pic:"T12",desc:"bowstring"},
    {chars:"rwD",pic:"T12",desc:"bowstring"},
    {chars:"Sms",pic:"T18",desc:"crook with bundle attached"},
    {chars:"dbA",pic:"T25",desc:"reed float"},
    {chars:"DbA",pic:"T25",desc:"reed float"},
    {chars:"sSm",pic:"T31",desc:"knife sharpener"},
    {chars:"Sna",pic:"U13",desc:"plow"},
    {chars:"grg",pic:"U17",desc:"pick and depression"},
    {chars:"stp",pic:"U21",desc:"adze and block of wood"},
    {chars:"sTp",pic:"U21",desc:"adze and block of wood"},
    {chars:"Ssr",pic:"V6",desc:"cord with ends up"},
    {chars:"wAH",pic:"V29",desc:"swab"},
    {chars:"msn",pic:"V32",desc:"wicker satchel"},
    {chars:"bAs",pic:"W2",desc:"oil jar without ties"},
    {chars:"Xnm",pic:"W9",desc:"stone jug"},
    {chars:"Hnw",pic:"W10",desc:"cup"},
    {chars:"xnt",pic:"W18",desc:"water jars in a rack"},
    {chars:"swA",pic:"Z9",desc:"crossed sticks"},
    {chars:"zwA",pic:"Z9",desc:"crossed sticks"},
    {chars:"Sbn",pic:"Z9",desc:"crossed sticks"},
    {chars:"xbs",pic:"Z9",desc:"crossed sticks"},
    {chars:"wHA",pic:"Aa2",desc:"pustule"},
    {chars:"Hip",pic:"Aa5",desc:"part of a ship"},
    {chars:"mAa",pic:"Aa11",desc:"platform"},
    {chars:"apr",pic:"Aa20",desc:"bag for clothing"},
    {chars:"wDa",pic:"Aa21",desc:"unknown"},
    {chars:"sti",pic:"Aa32",desc:"bow"},
    {chars:"sTi",pic:"Aa32",desc:"bow"}
];